version: "3.4"

x-defaults: &defaults
  environment:
    EULA: "TRUE"
    TYPE: "PAPER"
    VERION: "${MINECRAFT_VERSION}"
    UID: "${DOCKER_UID}"
    GID: "${DOCKER_GID}"
  image: itzg/minecraft-server

services:
  router:
    command: "-mapping bedwars.${HOSTNAME}=bedwars:25565,thewalls.${HOSTNAME}=thewalls:25565,hungergames.${HOSTNAME}=hungergames:25565"
    image: itzg/mc-router
    ports:
      - "25565:25565"

  bedwars:
    <<: *defaults
    ports:
      - "25566:25565"
    volumes:
      - "./data/bedwars:/data"

  thewalls:
    <<: *defaults
    ports:
      - "25567:25565"
    volumes:
      - "./data/thewalls:/data"

  hungergames:
    <<: *defaults
    ports:
      - "25568:25565"
    volumes:
      - "./data/hungergames:/data"
