version: "3.4"

x-defaults: &defaults
  environment:
    EULA: "TRUE"
    TYPE: "PAPER"
    VERSION: "${MINECRAFT_VERSION}"
    UID: "${DOCKER_UID}"
    GID: "${DOCKER_GID}"
    MEMORY: "2G"
  image: itzg/minecraft-server

services:
  router:
    command: "-mapping bedwars.${HOSTNAME}=bedwars:25565,thewalls.${HOSTNAME}=thewalls:25565,hungergames.${HOSTNAME}=hungergames:25565"
    environment:
      CONNECTION_RATE_LIMIT: "20"
    image: itzg/mc-router
    ports:
      - "25565:25565"

  bedwars:
    <<: *defaults
    ports:
      - "25566:25565"
    volumes:
      - "./data/bedwars:/data"
      # Mount server.properties as read-only because paper is stupid and keeps reordering the contents
      - "./data/bedwars/server.properties:/data/server.properties:ro"

  thewalls:
    <<: *defaults
    ports:
      - "25567:25565"
    volumes:
      - "./data/thewalls:/data"
      # Mount server.properties as read-only because paper is stupid and keeps reordering the contents
      - "./data/thewalls/server.properties:/data/server.properties:ro"

  hungergames:
    <<: *defaults
    ports:
      - "25568:25565"
    volumes:
      - "./data/hungergames:/data"
      # Mount server.properties as read-only because paper is stupid and keeps reordering the contents
      - "./data/hungergames/server.properties:/data/server.properties:ro"
